name: Build with ESP-IDF v4.1

on: [push]

jobs:
  builder:
    name: Builder for the test project
    runs-on: ubuntu-20.04

    env:
      esp-idf-ver: v4.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache the ESP-IDF
        uses: actions/cache@v2
        with:
          path: [~/esp, ~/.espressif]
          key: ${{ runner.os }}-${{ env.esp-idf-ver }}

      - name: Install ESP-IDF
        uses: CalinRadoni/esp-idf-v4-action@v2
        with:
          esp_idf_version: ${{ env.esp-idf-ver }}

      - name: Build
        run: |
          source ~/esp/esp-idf/export.sh
          cd SW
          idf.py reconfigure
          idf.py app
          idf.py size
